In [1]:
import pandas as pd
import random
import torch
import json
from torch.utils.data import Dataset, DataLoader
from transformers import DebertaTokenizer, DebertaForSequenceClassification
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score, matthews_corrcoef, confusion_matrix
from sklearn.preprocessing import label_binarize
import torch.optim as optim
import numpy as np

# Load the data
with open('/content/casualnet.json', 'r') as f:
    casulnet_data = json.load(f)


random_selected_samples = random.sample(casulnet_data, 1000)

# Define split sizes for an 80-20 split
train_size = int(0.8 * len(random_selected_samples))
train_data = random_selected_samples[:train_size]
validation_data = random_selected_samples[train_size:]

class CasulnetDataset(Dataset):
    def __init__(self, casulnet_data, tokenizer):
        self.casulnet_data = casulnet_data
        self.tokenizer = tokenizer

    def __len__(self):
        return len(self.casulnet_data)

    def __getitem__(self, idx):
        data = self.casulnet_data[idx]
        context_question = data['context']
        choices = [data[f'choice_id: {i}'] for i in range(3)]  # Assuming there are always 3 choices
        label = data['label']

        # Tokenizing context_question with each choice
        input_ids = []
        attention_masks = []
        for choice in choices:
            encoded_input = self.tokenizer(context_question, choice, padding='max_length', truncation=True, max_length=512, return_tensors='pt')
            input_ids.append(encoded_input['input_ids'].squeeze(0))
            attention_masks.append(encoded_input['attention_mask'].squeeze(0))

        label = torch.tensor([label]*3)  # Replicate label for each choice
        return {
            'input_ids': torch.stack(input_ids),
            'attention_mask': torch.stack(attention_masks),
            'labels': label
        }

# Load tokenizer and model
tokenizer = DebertaTokenizer.from_pretrained('microsoft/deberta-base')
model = DebertaForSequenceClassification.from_pretrained('microsoft/deberta-base', num_labels=3)  # Assuming 3 possible labels

casulnet_dataset = CasulnetDataset(train_data, tokenizer)
dataloader = DataLoader(casulnet_dataset, batch_size=8, shuffle=True)

optimizer = optim.Adam(model.parameters(), lr=1e-5)

# Training loop
model.train()
for epoch in range(3):
    for batch in dataloader:
        optimizer.zero_grad()
        input_ids = batch['input_ids'].view(-1, 512)  # Flatten the input for processing
        attention_mask = batch['attention_mask'].view(-1, 512)  # Flatten the attention mask for processing
        labels = batch['labels'].view(-1)  # Flatten the labels to match the input batch size

        outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        print(f"Epoch: {epoch}, Loss: {loss.item()}")

validation_dataset = CasulnetDataset(validation_data, tokenizer)
validation_dataloader = DataLoader(validation_dataset, batch_size=64)

model.eval()
y_true, y_pred, y_scores = [], [], []

def compute_metrics(y_true, y_pred, y_prob):
    accuracy = accuracy_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred, average='weighted')
    precision = precision_score(y_true, y_pred, average='weighted')
    recall = recall_score(y_true, y_pred, average='weighted')
    roc_auc = roc_auc_score(label_binarize(y_true, classes=[0, 1, 2]), y_prob, multi_class='ovr', average='weighted')
    mcc = matthews_corrcoef(y_true, y_pred)
    conf_matrix = confusion_matrix(y_true, y_pred)
    return accuracy, f1, precision, recall, roc_auc, mcc, conf_matrix

with torch.no_grad():
    for batch in validation_dataloader:
        input_ids = batch['input_ids'].view(-1, 512)
        attention_mask = batch['attention_mask'].view(-1, 512)
        labels = batch['labels'].view(-1)
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        predictions = torch.argmax(outputs.logits, dim=1)
        y_scores_batch = torch.softmax(outputs.logits, dim=1).cpu().numpy()

        y_true.extend(labels.cpu().numpy())
        y_pred.extend(predictions.cpu().numpy())
        y_scores.extend(y_scores_batch)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/474 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/559M [00:00<?, ?B/s]

Some weights of DebertaForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-base and are newly initialized: ['pooler.dense.weight', 'classifier.weight', 'classifier.bias', 'pooler.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Epoch: 0, Loss: 1.0830403566360474
Epoch: 0, Loss: 1.1003656387329102
Epoch: 0, Loss: 1.1247578859329224
Epoch: 0, Loss: 1.09907066822052
Epoch: 0, Loss: 1.109478235244751
Epoch: 0, Loss: 1.0916273593902588
Epoch: 0, Loss: 1.1017667055130005
Epoch: 0, Loss: 1.1071770191192627
Epoch: 0, Loss: 1.0845683813095093
Epoch: 0, Loss: 1.122377634048462
Epoch: 0, Loss: 1.1103440523147583
Epoch: 0, Loss: 1.0559896230697632
Epoch: 0, Loss: 1.1233547925949097
Epoch: 0, Loss: 1.087058424949646
Epoch: 0, Loss: 1.0885133743286133
Epoch: 0, Loss: 1.1115214824676514
Epoch: 0, Loss: 1.0795857906341553
Epoch: 0, Loss: 1.1285061836242676
Epoch: 0, Loss: 1.1547127962112427
Epoch: 0, Loss: 1.0994092226028442
Epoch: 0, Loss: 1.1284394264221191
Epoch: 0, Loss: 1.1144784688949585
Epoch: 0, Loss: 1.114932656288147
Epoch: 0, Loss: 1.075541377067566
Epoch: 0, Loss: 1.1045929193496704
Epoch: 0, Loss: 1.0973328351974487
Epoch: 0, Loss: 1.0979124307632446
Epoch: 0, Loss: 1.0634043216705322
Epoch: 0, Loss: 1.059209227

In [2]:
# Calculate metrics
y_scores = np.vstack(y_scores)  # Ensure y_scores is properly shaped for multiclass ROC-AUC calculation
accuracy, f1, precision, recall, roc_auc, mcc, conf_matrix = compute_metrics(y_true, y_pred, y_scores)

print(f"Accuracy: {accuracy:.4f}")
print(f"F1: {f1:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"ROC-AUC: {roc_auc:.4f}")
print(f"MCC: {mcc:.4f}")
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.3350
F1: 0.2583
Precision: 0.2200
Recall: 0.3350
ROC-AUC: 0.4692
MCC: 0.0030
Confusion Matrix:
[[  0  72 129]
 [  0  63 135]
 [  0  63 138]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
